# Generated by Django 2.2.4 on 2019-08-09 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INEZ.List')),
            ],
            options={
                'ordering': ['-price', 'title'],
            },
        ),
    ]
