# Generated by Django 2.2.4 on 2019-08-09 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['-price', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
