# Generated by Django 2.2.4 on 2019-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEZ', '0002_auto_20190809_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery_list',
            options={'ordering': ['date', 'title']},
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
