# Generated by Django 2.2.4 on 2019-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEZ', '0003_auto_20190811_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_list',
            name='unit',
            field=models.CharField(default='kg', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocery_list',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
