# Generated by Django 2.2.4 on 2019-08-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEZ', '0004_auto_20190814_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_list',
            name='search',
            field=models.CharField(default='met', max_length=500),
            preserve_default=False,
        ),
    ]
